[tool.poetry]
name = "votigo"
version = "0.1.0"
description = "Learning practical event source with a real-world project"
authors = ["Leo Kuboschek <leo@kuboschek.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
eventsourcing = {extras = ["crypto"], version = "^9.2.22"}
uvicorn = "^0.28.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
