name: Package Cleanup

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  remove_untagged_images:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List untagged API images
        id: list-api-images
        run: |
          curl -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}-api/manifests?tags=untagged" | jq -r '.manifests[].digest' > api-images.txt

      - name: List untagged UI images
        id: list-ui-images
        run: |
          curl -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}-ui/manifests?tags=untagged" | jq -r '.manifests[].digest' > ui-images.txt

      - name: Remove untagged API images from GHCR
        run: |
          cat api-images.txt | xargs -I {} curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}-api/manifests/{}"

      - name: Remove untagged UI images from GHCR
        run: |
          cat ui-images.txt | xargs -I {} curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}-ui/manifests/{}"

      - name: Cleanup images files
        run: rm api-images.txt ui-images.txt
