name: Package Cleanup

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  remove_untagged_images:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List untagged images
        id: list-images
        run: |
          curl -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}/manifests?tags=untagged" | jq -r '.manifests[].digest' > images.txt

      - name: Remove untagged images from GHCR
        run: |
          cat images.txt | xargs -I {} curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}/manifests/{}"

      - name: Cleanup images file
        run: rm images.txt
